commitizen:
  changelog_file: CHANGELOG.md
  changelog_incremental: true
  name: cz_conventional_commits
  tag_format: $major.$minor.$patch$prerelease
  update_changelog_on_bump: true
  version: 0.12.9
  version_files:
  - setup.py:version
  - ost/__init__.py:__version__ 
