commitizen:
  changelog_file: CHANGELOG.md
  name: cz_conventional_commits
  tag_format: v$major.$minor.$patch$prerelease
  version: 0.12.6
  version_files:
  - setup.py:version
  - ost/__init__.py:__version__
